config/routes.rb
Rails.application.routes.draw do
  root 'services#root'
  get 'send_zoho', to: 'services#send_zoho'
  get 'update_zoho', to: 'services#update_zoho'
  get 'mail_campaign', to: 'services#mail_campaign'
  post 'calendly_zoho', to: 'services#calendly'
  post 'calendly_cancelled', to: 'services#calendly_cancelled'
  get 'payments_zoho', to: 'services#payments'
  get 'app_answers', to: 'services#app_answers'
  get 'slack_it', to: 'services#slack_it'
  get 'codeatalks', to: 'services#codeatalks'
  get 'codeatalks_confirm', to: 'services#codeatalks_confirm'
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/helpers/services_helper.rb
module ServicesHelper

  def search_zoho(email,type)
    base_request = "https://crm.zoho.com/crm/private/json/#{type}/searchRecords?authtoken=#{ENV['ZOHO_TOKEN']}&scope=crmapi&criteria=(Email:#{email})"
    request = URI.parse(URI.escape(base_request))
    check = JSON.parse(Net::HTTP.get(request))
    parse_response(check,type)
  end

  def parse_response(check,type)
    if check['response']['nodata'] || check['response']['error']
      false
    else
      response = params[:action] == 'calendly' ? parse_calendly_check(check,type) : parse_send_check(check)
      unless response.kind_of?(Array)
        zoho_id = response['FL'].first['content']
        owner_id = response['FL'][1]['content']
      else
        zoho_id = response.first['FL'].first['content']
        owner_id = response.first['FL'][1]['content']
      end
      owner_id = /^[0-9]*$/.match(owner_id) ? owner_id : Salesman.actual_id
      {zoho_id: zoho_id, owner_id: owner_id}
    end
  end

  def parse_calendly_check(check,type)
    check['response']['result'][type]['row']
  end

  def parse_send_check(check)
    check['response']['result']['recorddetail']
  end

  def parse_cancelled(check)
    if check['response']['nodata'] || check['response']['error']
      false
    else
      check['response']['result']['Calls']['row']['FL'].first['content']
    end
  end

  def find_zoho_owner(id,type)
    base_request = "https://crm.zoho.com/crm/private/json/#{type}/getRecordById?&authtoken=#{ENV['ZOHO_TOKEN']}&scope=crmapi&id=#{id}"
    request = URI.parse(URI.escape(base_request))
    check = JSON.parse(Net::HTTP.get(request))
    parsed = parse_response(check,type)#[1]
    parsed ? parsed : false
  end

  def parse_salesforceuuid
    zoho = params[:zoho_id].split(',')
    return parse_zoho_mail if zoho.empty?
    owner =  zoho[2].to_i == 0 ? id_with_name[zoho[2]] : zoho[2]
    params.update(zoho_id: zoho[0], zoho_type: zoho[1], zoho_owner: owner)
  end

  def parse_zoho_mail
    contact = search_zoho(params[:email],'Contacts')
    if contact
      zoho_id = contact[:zoho_id].is_a?(Array) ? contact[:zoho_id].first : contact[:zoho_id]
      type = "Contacts"
      owner_id = contact[:owner_id]
    else
      lead = search_zoho(params[:email],'Leads')
      if lead
        zoho_id = lead[:zoho_id].is_a?(Array) ? lead[:zoho_id].first : lead[:zoho_id]
        type = "Leads"
        owner_id = lead[:owner_id]
      else
        {error: "No Zoho ID, or no email found. Email: #{params[:email]} Name: #{params[:name]}", email: params[:email]}
      end
    end
    params.update(zoho_id: zoho_id, zoho_type: type, zoho_owner: owner_id)
  end

  def create_call_zoho(zoho_id,zoho_type,zoho_owner,name,start_time,end_time,link,q_a,cancellation,reschedule,event_id)
    # Creo la línea base del API request a Zoho
    base_request = "https://crm.zoho.com/crm/private/json/Calls/insertRecords?authtoken=#{ENV['ZOHO_TOKEN']}&scope=crmapi&wfTrigger=true&newFormat=1&xmlData="
    # Genero y concateno una variable con los parametros de la petición
    changes = "<FL val='Subject'>Calendly_new: #{name} - #{start_time.strftime("%m/%d/%Y %H:%M:%S")}</FL>"
    changes += "<FL val='Call Start Time'>#{(start_time - 15.minutes).strftime("%m/%d/%Y %H:%M:%S")}</FL>"
    changes += "<FL val='Call End Time'>#{(end_time).strftime("%m/%d/%Y %H:%M:%S")}</FL>"
    changes += "<FL val='Created at'>#{Time.zone.now.strftime("%m/%d/%Y %H:%M:%S")}</FL>"
    changes += "<FL val='Description'>#{q_a}: #{link}</FL>"
    changes += "<FL val='Call Result'>#{event_id}</FL>"
    changes += "<FL val='whichCall'>ScheduleCall</FL>"
    # # el formato en que se manda el owner depende del modulo
    if zoho_type == 'Contacts'
      changes += "<FL val='CONTACTID'>#{zoho_id}</FL>"
      changes += "<FL val='SEMODULE'>Contacts</FL>"
    else
      changes += "<FL val='LEADID'>#{zoho_id}</FL>"
      changes += "<FL val='SEMODULE'>Leads</FL>"
    end
    changes += "<FL val='SEID'>#{zoho_id}</FL>"
    p changes += "<FL val='SMOWNERID'>#{zoho_owner}</FL>"
    # Agregamos los cambios al objeto Calls de XML
    base_xmldata = "<Calls><row no='1'>#{changes}</row></Calls>"
    # Update a los datos del Contacto o Leads
    update_contact(zoho_type,zoho_id,start_time,link,cancellation,reschedule)
    # Generamos la URI para hacer el request
    request = URI.parse(URI.escape(base_request + base_xmldata))
    # Enviamos la URI vía GET y parseamos a JSON los resultados
    check = JSON.parse(Net::HTTP.get(request))
  end

  def create_event
    params[:zoho_id] ? parse_salesforceuuid : parse_zoho_mail
    if params[:error]
       {error: "No Zoho ID, or no email found. Email: #{params[:email]} Name: #{params[:name]}", email: params[:email]}
    else
      create_call_zoho(params[:zoho_id],params[:zoho_type],params[:zoho_owner],params[:name],DateTime.parse(params[:start_time]),DateTime.parse(params[:end_time]),params[:link],params[:q_a],params[:cancellation],params[:reschedule],params[:event_id])
    end
  end

  def update_contact(type,id,start,link,cancellation,reschedule)
    base_request = "https://crm.zoho.com/crm/private/json/#{type}/updateRecords?authtoken=#{ENV['ZOHO_TOKEN']}&scope=crmapi&wfTrigger=true&id=#{id}&xmlData="
    changes = "<FL val='Calendly Hangouts'>#{link}</FL>"
    changes += "<FL val='Calendly DateTime'>#{start.strftime("%m/%d/%Y %H:%M:%S")}</FL>"
    changes += "<FL val='Calendly Cancellation'>#{cancellation}</FL>"
    changes += "<FL val='Calendly Reschedule'>#{reschedule}</FL>"
    base_xmldata = "<#{type}><row no='1'>#{changes}</row></#{type}>"
    request = URI.parse(URI.escape(base_request + base_xmldata))
    check = JSON.parse(Net::HTTP.get(request))
  end

  def parse_zoho_params(params)
    changes = Hash.new
    params.each do |k,v|
      field = case k
        when 'name' then 'Last Name'
        when 'source' then 'Lead Source'
        when 'medium' then 'Lead Medium'
        when 'campaign' then 'Campaign'
        else k.capitalize
      end
      changes[field] = v
    end
    changes
  end

  def calculate_answers(params)
    correct_answers = {question1: 'Alto nivel, interpretado, y orientado a objetos.', question2: '"Hola mundo"', question3: '2.7', question4: 'true', question5: 'Hash', question6: 'title = "Yo soy el título"', question7: 'ID = 5', question8: 'Son elementos que relacionan los valores de una o más variables o constantes para manipularlos.', question9: 'Exponencial', question10: '25', question11: 'Comparan valores entre sí', question12: '->', question13: '# Comentando'}
    answers = 0
    correct_answers.each { |k,v| answers += 1 if v == params[k] }
    answers
  end

  # API Slack
  def slack_it!(data,event)
    uri = URI.parse('https://hooks.slack.com/services/T04N9D6A8/' + slack_channels[event.to_sym])
    req = Net::HTTP::Post.new(uri.to_s)
    req.body = {text: data + "\n [<@ibarroladt>]"}.to_json
    req['Content-Type'] = 'application/json'
    response = https(uri).request(req)
  end

  def slack_channels
    {leads: 'B5XMN2SSK/ZHWaQMAgI7sVTk8KZGqSXBXc', answers: 'B5W73GKLG/XTqu8ntvrEtfsXA7B1APWnz3', calendly: 'B5WAJSEBT/h0GygCxPdBG3Tm7JhwvqGumQ', codeatalks: 'B5Z4NC2Q6/JP1McoDYrJ40UNJE9rtjXwTt', miscellaneous: 'B5Z3XEE4F/ecm2ltWMgDrSdA05VVm0pqpV'}
  end

  def owner_with_name
    { 'Jonathan Reyes' => 'jonathan88', 'Enrique Hernández' => 'enrique-codea', 'Omar Vazquez' => 'omvzqz' }
  end

  def id_with_name
    { 'Jonathan Reyes' => '2066727000000531969', 'Enrique Hernández' => '2066727000004666316', 'Omar Vazquez' => '2066727000001483009' }
  end

  def owner_with_id
    { '2066727000000531969' => 'jonathan88', '2066727000004666316' => 'enrique-codea', '2066727000001483009' => 'omvzqz' }
  end

  def campaign_params
    {
      'CampañaS5': {group_ad: 'CodeaCamp5', ad_set: 'Slideshow2', ad: 'Slideshow New'},
      'S7_MX': {group_ad: 'Campaña S7 MX', ad_set: 'Campaña S7', ad: 'Slideshow New'},
      nil: {group_ad: nil, ad_set: nil, ad: nil},
      "": {group_ad: nil, ad_set: nil, ad: nil}
    }
  end

  private

  def https(uri)
    Net::HTTP.new(uri.host, uri.port).tap do |http|
      http.use_ssl = true
      http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    end
  end

end

app/views/services/_to_landing.html.erb
<br>
<div class="well">
	<h3 >¿Aún no te has registrado en Codea?</h3>
	<br>
	<%= link_to 'Descubre que puedes lograr si aprendes Desarrollo Web', @link, class: 'btn btn-lg btn-success' %>
</div>
<br>

app/views/services/app_answers.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <div class="jumbotron" style="background-color: #1f8dd3;margin-top: 50px;color:white;">
        <h2><%= @title %> <%= "(#{@answers}/13)" %></h2>
        <% if @answers >= 10 %>
          <h3>Has ganado nuestra beca de 15%.
        <% end %>
        <br><br>
        <% if @closing_date %>
          Tienes hasta el día <b><%= @closing_date %></b> para hacer válida tu beca.
          <br><br>
        </h3>
        <% end %>
      </div>

        <p style="font-size:25px;">
      <% if @answers >= 10 %>
          <% if @amount %>
            <% discount = @amount * 0.85 %>
            Tu monto a pagar es de <b><%= number_to_currency(discount) %></b>.
          <% else %>
            Si no estás seguro cuál es el tu monto a pagar, comunícate con tu asesor.
          <% end %>
          <br><br>
          Para aprovechar tu beca finaliza tu inscripción en el siguiente link:
          <br><br>
          <%= link_to 'Finaliza tu proceso', "http://www.codeacamp.mx/payments/?amount=#{@amount*0.85}&name=#{@name}", class: 'btn btn-lg btn-success', style: 'font-size:40px;' %>
          <br><br>
          Si tienes alguna duda, escríbenos a <a href="mailto:contacto@codea.mx">contacto@codea.mx</a>, o llámanos al <a href="tel:5567267075">55 6726 7075</a>
          <br>
      <% else %>
        No tuviste suficientes respuestas correctas, <%= link_to "puedes intentarlo una vez más", :back %>
      <% end %>
        </p>
    </div>
  </div>
</div>

app/views/services/codeatalks.html.erb
<br>
<div class="row">
  <div class="jumbotron text-center confirm-btn" style="overflow:auto">
    <span style="font-size:45px;">
      <span style="font-family:'Ubuntu', sans-serif;">
        <span style="color:#ffc842;">
          <strong>CODEA</strong></span><span style="color:#2b2b2b;">Talks</span><span style="color:#ffc842;">
        </span>
      </span>
    </span>
    <h2>Muchas gracias por tu interes en la plática:</h2>

    <div class="row">
      <h1>La Cultura StartUp y la Tecnología.</h1>
      <h4>Jun 27, 2017, 7:00pm</h4>
      <br class="clear"></br>
      <div class="col-md-6">
        <h3>AndrésMartínez | TalentManager | Bitso</h3>
        <br>
        <p>Mañana nos dará su visión sobre esta cultura de empresas emergentes, el talento que la rodea y sus diferentes enfoques en la tecnología y la innovación para sobrevivir y además, ser exitosas.</p>
        <br><br>
        <p style="font-size: 14px;">Actualmente, Andrés se desempeña como Director de Recursos Humanos en Bitso, plataforma digital para automatizar y llevar a cabo operaciones financieras entre diferentes monedas, un nuevo mundo financiero global, a través de la tecnología.
        <br> A la par es fundador, socio mayoritario y director en ConDuckting, consultoría en desarrollo humano, para generar equipos de alto impacto comprometidos con la misión y visión de la empresa.
        <br> Ha sido parte fundamental de la cultura emprendedora en México como speaker motivacional, como consultor y como mentor, gestionando la formación del talento mexicano para alcanzar su máximo potencial, en todos los niveles, desde los más junior hasta los más experimentados.</p>
      </div>
      <div class="col-md-6">
        <div class="thumbnail vcenter">
          <br><br>
          <img src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAmlAAAAJGI5ODM5OWVmLWE3MDMtNGVmYy04NjVjLWExZTUzMzFmMDIwNw.jpg" alt="Andrés Martínez">
          <br><br>
        </div>
      </div>
      <br class="clear"></br>
    </div>

    <% if params[:zoho_id] %>
      <p>Da click en el siguiente botón para validar tu asistencia</p>
      <br><br>
      <%= link_to 'Confirmar Asistencia', codeatalks_confirm_path(data: params), class: 'btn btn-lg btn-success', remote: true %>
    <% else %>
      <br><br>
      <div class="col-xs-12 col-sm-12 col-md-offset-3 col-md-6 text-left">
        <%= simple_form_for :data, url: codeatalks_confirm_path(data: params), method: :get, remote: true, :defaults => {:required => false} do |f| %>
          <%= f.input :name, as: :string %>
          <%= f.input :email, as: :string %>
          <%= f.input :phone, as: :string %>
          <%= f.hidden_field :title, value: params[:title] %>
          <%= f.hidden_field :date, value: params[:date] %>
          <%= f.hidden_field :utm_source, value: params[:utm_source] %>
          <%= f.hidden_field :utm_medium, value: params[:utm_medium] %>
          <%= f.hidden_field :utm_campaign, value: params[:utm_campaign] %>
          <div class="text-center">
            <%= f.submit "Confirmar Asistencia", class: 'btn btn-lg btn-success'  %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row col-xs-12 col-sm-12 col-md-6 col-md-offset-3 text-center" id="post-confirmation" style="display: none">
      <h1>¡Gracias!</h1>
      <br>
      <h4>Te esperamos en la siguiente fecha y dirección:</h4>
      <h3><%= params[:date] %></h3>
      <h4>Avenida Sonora 84A, Roma Norte, CDMX</h4>
      <div id="post-landing"></div>
      <iframe id="gmap" width="100%" height="400px" frameborder="1" style="border:1" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBRlHzqlb0y3w4V4DKlvGkqRmvunduc6ZE&q=CodeaCamp" allowfullscreen></iframe>
  </div>
</div>


<br><br>

app/views/services/codeatalks_confirm.js.erb
$('.confirm-btn').hide();
$('#post-confirmation').show();
<% if @link %>
	$('#post-landing').html("<%= j render('services/to_landing', link: @link) %>");
<% end %>

app/views/services/daily_email.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Leads & Contacts Day by Day</h1>
      <iframe frameborder=0 width="800" height="600" src="https://reports.zoho.com/ZDBDataSheetView.cc?OBJID=1322665000000040041&STANDALONE=true&privatelink=c066da8b4d820f40a484eb353bd34c7f&WIDTH=800&HEIGHT=600&INTERVAL=-1&REMTOOLBAR=true&INCLUDETITLE=true&INCLUDEDESC=true"></iframe>
    </div>
    <div class="col-md-12">
      <h1>Leads Overview</h1>
      <iframe frameborder=0 width="800" height="600" src="https://reports.zoho.com/ZDBDataSheetView.cc?OBJID=1322665000000112651&STANDALONE=true&privatelink=7e8950c8110c906c022a8db41c51a054&WIDTH=800&HEIGHT=600&INTERVAL=-1&REMTOOLBAR=true&INCLUDETITLE=true&INCLUDEDESC=true"></iframe>
    </div>
  </div>
</div>

app/views/services/root.html.erb
<div class="crying text-center">
  <h1>Nothing to do here</h1>
  <img src="https://s9.postimg.org/k7dj4crz3/cryingcomputer.gif" alt="We're Sorry!">
</div>